<?php

require_once "Vehicule.php";

class Velo extends Vehicule
{

    private $dimension;

    /**
     * @return mixed
     */
    public function getDimension()
    {
        return $this->dimension;
    }

    /**
     * @param mixed $dimension
     */
    public function setDimension($dimension): void
    {
        $this->dimension = $dimension;
    }

    public function __toString(){
        return sprintf(" %s Dimension %s\n", parent::__tostring(), $this->dimension);
    }

    public function saisieClavier()
    {
        parent::saisieClavier(); // TODO: Change the autogenerated stub

        echo "Saisir une dimension";
        $this->setDimension(readline());
    }
}
